Fix kafka-client kafka4beam-brod fetch request failed (#1321)
Currently, the fetch request will fail when we use erlang Kafka-client(`kafka4beam/brod`) to consume the standard message. Because the `kafka4beam/brod` Kafka client always uses `read_commited` to fetch the message even if the client is not using transactions.

See: https://github.com/kafka4beam/kafka_protocol/blob/713a00e30a5f7ab0d19558c502a7e5cc5b0bfa68/src/kpro_req_lib.erl#L166-L172
```erlang
%% `IsolationLevel = kpro_read_uncommitted' to fetch uncommitted messages.
-spec fetch(vsn(), topic(), partition(), offset(), fetch_opts()) -> req().
fetch(Vsn, Topic, Partition, Offset, Opts) ->
  MaxWaitTime = maps:get(max_wait_time, Opts, timer:seconds(1)),
  MinBytes = maps:get(min_bytes, Opts, 0),
  MaxBytes = maps:get(max_bytes, Opts, 1 bsl 20), %% 1M
  IsolationLevel = maps:get(isolation_level, Opts, ?kpro_read_committed),
```

Error log:
```
java.lang.IllegalArgumentException: Broker has disabled transaction coordinator, please enable it before using transaction.
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.throwIfTransactionCoordinatorDisabled(KafkaRequestHandler.java:2478) ~[ZTCCJ6BUXIIL7zuZcqCOWA/:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.getTransactionCoordinator(KafkaRequestHandler.java:275) ~[ZTCCJ6BUXIIL7zuZcqCOWA/:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.handleFetchRequest(KafkaRequestHandler.java:1551) ~[ZTCCJ6BUXIIL7zuZcqCOWA/:?]
	at io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder.channelRead(KafkaCommandDecoder.java:286) [ZTCCJ6BUXIIL7zuZcqCOWA/:?]
```

In the current KoP implementation, we will check the Kafka transaction coordinator is enabled first. However, for compatibility with kafka4beam/brod, we need to skip this check in fetch request.

Skip checking the Kafka transaction coordinator is enable in the fetch request.

(cherry picked from commit 7716e64ae74fc5016d32594f96da4a5aa7c45b35)