Avoid lombok usages in interfaces for JavaDoc plugin (#1466)
When deploying KoP into Maven central with Java 11, it failed when building JavaDocs:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project kafka-client-api: MavenReportException: Error while generating Javadoc:
Error:  Exit code: 1 - /home/runner/work/streamnative-ci/streamnative-ci/kop/kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Producer.java:25: error: cannot find symbol
Error:      default ProduceContext.ProduceContextBuilder<K, V> newContextBuilder(String topic, V value) {
Error:                            ^
Error:    symbol:   class ProduceContextBuilder
Error:    location: class ProduceContext
Error:  /home/runner/work/streamnative-ci/streamnative-ci/kop/kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Producer.java:29: error: cannot find symbol
Error:      default ProduceContext.ProduceContextBuilder<K, V> newContextBuilder(String topic, V value, Integer partition) {
Error:                            ^
Error:    symbol:   class ProduceContextBuilder
Error:    location: class ProduceContext
Error:
Error:  Command line was: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-8/x64/bin/javadoc -Xdoclint:none @options @packages
```

It seems like the annotation processors don't run when the javadoc tool is invoked. See https://github.com/projectlombok/lombok/issues/2137.

- Add the `ProducerContext.ProduceContextBuilder` class instead of the class generated by lombok to fix the failure.
- Upgrade the maven-javadoc-plugin to 3.4.1 and the related configs to make `mvn javadoc:jar` passed.
- Add a step into the workflow to build JavaDocs

(cherry picked from commit 6a2db01f40d3f507078611258429d11372f63a3e)