Improve handle OAuth callback throw authentication exception behavior (#1276)
Currently, when the `OauthValidatorCallbackHandler#handleCallback` method throws an exception, the client will receive warn log below and it will always try to reconnect.
```
15:51:14.143 [kafka-consumer-2] WARN org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-topic-1-1, groupId=topic-1] Connection to node 782843879 (localhost/127.0.0.1:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
```

Broker side log:
```
2022-05-09T14:29:39,673+0800 [pulsar-io-18-10] ERROR io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Caught error in handler, closing channel
java.lang.IllegalStateException: Authentication exchange has not completed
	at io.streamnative.pulsar.handlers.kop.security.oauth.KopOAuthBearerSaslServer.getAuthorizationID(KopOAuthBearerSaslServer.java:94) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.security.SaslAuthenticator.handleSaslToken(SaslAuthenticator.java:503) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.security.SaslAuthenticator.authenticate(SaslAuthenticator.java:223) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.channelPrepare(KafkaRequestHandler.java:382) ~[?:?]
// ...
```

In this case, we should have `SaslAuthenticationException` instead of the warning log.

* Make sure to send the authentication error response to the client before closing the channel.
* Add check to make sure the `SaslServer` is complete before getting the authorization ID.
* Add units test to cover this case.

(cherry picked from commit 1d153573e5e9ab9f6125b19e85b77fbe28360f74)